machineDeployment:
# Manage annotations for machineDeployment
  annotations: {}

addons:
  cni: {}
  ccm: {}
  metallb: {}
  ingress: {}
  certmanager: {}
  csi: {}
  kubevip: {}

machinehealthcheck:
  enabled: false

#sshkeyname: REPLACE_MY_KEY

#bastion:
#  enabled: false
#  image: ubuntu22.04
#  flavor: CO1.2
#  network: tooling
#  subnet: tooling # optional, defaults to "tooling"
#  fixedIP: 192.168.101.9
#controlplane:
#  version: v1.29.4
#  replicas: 1
#  image: ubuntu-2204-kube-v1.29.4
#  flavor: CO1.2
#  network: controlplane
#  subnet: controlplane # optional, defaults to "controlplane"
#  # reserved ip/port outside cluster-api
#  apiServerFixedIP: 192.168.101.10
#  # if controlplane VirtualIP is different from apiServerFixedIP
#  apiServerVirtualIP: 192.168.200.10
#  availabilityZones:
#    - AZ1
#    - AZ2
#  serverGroup:
#    filter:
#      name: worker-node
#  #rootVolume: {}
#workers:
#  md-0:
#    version: v1.29.4
#    replicas: 0
#    image: ubuntu-2204-kube-v1.29.4
#    flavor: CO1.2
#    network: workers
#    subnet: workers # optional, defaults to "workers"
#    # reserved ip/port outside cluster-api
#    ingressServerFixedIP: 192.168.101.11
#    failureDomain: AZ1
#    serverGroup:
#      filter:
#        name: worker-node
#    serverMetadata:
#      - key: ingress-ready
#        value: "true"
#    nodeLabels:
#      ingress-ready: true
#    #rootVolume: {}
#    #additionalBlockDevices: {}

certmanager: {}
csi: {}
cloudConfig:
  # b64 encoded value
  cacert:
  cloudsYaml:
  cloudConf: {}
