PriorityClass:
  name: low-priority
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  value: -1

replicaCount: 1

image:
  repository: registry.k8s.io/pause
  pullPolicy: IfNotPresent
  tag: "3.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  argocd.argoproj.io/sync-wave: "0"

podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  runAsUser: 65534
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

command: {}

resources:
  requests:
    cpu: 0.5
    memory: 100Mi
